import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      include: ["src/**/*.ts"],
      exclude: [
        "src/**/*.test.ts",
        // Generated by `pnpm ext sync` — not hand-written, not unit-tested.
        "src/ext/**/*.generated.ts",
        // Bootstrap/infra wiring (env parsing re-export, real Supabase client
        // construction + AppState listener registration at import time) —
        // exercised by the app at runtime, not meaningfully unit-testable.
        "src/lib/env.ts",
        "src/lib/supabase.ts",
      ],
    },
  },
});
